version: '3'
services:
  gamerunner:
    build: .
    image: ${CURRENT_IMAGE:-gamerunner:latest}
    command: /gamerunner/docker-entrypoint.sh
    restart: always
    depends_on:
      - redis
    container_name: ${VERSION:-main}_gamerunner
    volumes:
      - ./files:/gamerunner/files
      - ./static:/gamerunner/static
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /nfs:/nfs

  celery:
    build: .
    image: ${CURRENT_IMAGE:-gamerunner:latest}
    command: celery -A celery_app worker --concurrency=10 -l info -Ofair
    restart: always
    depends_on:
      - redis
    container_name: ${VERSION:-main}_celery
    volumes:
      - ./files:/gamerunner/files
      - ./static:/gamerunner/static
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /nfs:/nfs

#  celerybeat:
#    build: .
#    image: ${CURRENT_IMAGE:-gamerunner:latest}
#    command: celery -A celery_app beat -l info
#    restart: always
#    depends_on:
#      - redis
#    container_name: ${VERSION:-main}_celerybeat
#    volumes:
#      - ./files:/gamerunner/files
#      - ./static:/gamerunner/static
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/bin/docker:/usr/bin/docker
#      - /nfs:/nfs

  redis:
    image: redis:3.0.6
    restart: always
    container_name: ${VERSION:-main}_redis
    volumes:
      - ./data/redis/data:/data

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - gamerunner
    ports:
      - ${PORT:-8000}:80
    container_name: ${VERSION:-main}_nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./static:/static
      - ./files/uploads:/uploads
