version: '3'
services:
  gamerunner:
    build: .
    image: ${CURRENT_IMAGE:-gamerunner:latest}
    command: /gamerunner/wait_for_db.sh && /gamerunner/docker-entrypoint.sh
    restart: always
    depends_on:
      - redis
    container_name: ${VERSION:-main}_gamerunner
    volumes:
      - ./files:/search/files
      - ./static:/search/static

  celery:
    build: .
    image: ${CURRENT_IMAGE:-gamerunner:latest}
    command: /gamerunner/wait_for_db.sh && celery -A celery_app worker --concurrency=10 -l info -Ofair
    restart: always
    depends_on:
      - redis
    container_name: ${VERSION:-main}_celery
    volumes:
      - ./files:/search/files
      - ./static:/search/static

  celerybeat:
    build: .
    image: ${CURRENT_IMAGE:-gamerunner:latest}
    command: /gamerunner/wait_for_db.sh && celery -A celery_app beat -l info
    restart: always
    depends_on:
      - redis
    container_name: ${VERSION:-main}_celerybeat
    volumes:
      - ./files:/search/files
      - ./static:/search/static

  redis:
    image: redis:3.0.6
    restart: always
    container_name: ${VERSION:-main}_redis
    volumes:
      - ./data/redis/data:/data

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - gamerunner
    ports:
      - ${PORT:-8000}:80
    container_name: ${VERSION:-main}_nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
