# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IP',
            new_name='IPBinding',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='ip_stricted',
            new_name='ip_restricted',
        ),
    ]
