# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 22:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20170205_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipbinding',
            name='Token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_set', to='api.Token'),
        ),
    ]
