# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170205_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipbinding',
            name='Token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_set', to='api.Token'),
        ),
    ]
