# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0002_auto_20170203_1703'),
        ('run', '0002_auto_20170204_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='operation',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='game.Operation'),
            preserve_default=False,
        ),
    ]
