# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_run_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (2, 'Success'), (1, 'Running'), (3, 'Failure')], default=0),
        ),
    ]
