# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_run_queue_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
    ]
