# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0006_auto_20170224_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='response',
            field=models.SmallIntegerField(choices=[(0, 'Wating'), (1, 'Sending'), (2, 'Sent')], default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='response_queue_reference_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
