# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-28 15:07
# Generated by Django 1.10.5 on 2018-01-31 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0007_auto_20180128_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='service_log',
            field=models.FileField(null=True, upload_to='logs/'),
        ),
    ]
