# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0008_run_service_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='count_tries',
            field=models.SmallIntegerField(default=0),
        ),
    ]
