# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0009_run_count_tries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='service_log',
        ),
        migrations.AlterField(
            model_name='run',
            name='response',
            field=models.SmallIntegerField(
                choices=[(0, 'Waiting'), (1, 'Sending'), (2, 'Sent')],
                default=0,
            ),
        ),
    ]
