# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0009_run_count_tries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='response',
            field=models.SmallIntegerField(choices=[(0, 'Wating'), (1, 'Sending'), (2, 'Sent'), (3, 'Failed')], default=0),
        ),
    ]
