# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('config', models.TextField(verbose_name='docker compose yml template')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='game')),
            ],
        ),
        migrations.CreateModel(
            name='OperationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.CharField(choices=[('string', 'string'), ('file', 'file')], max_length=20, verbose_name='type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('input_parameter', models.BooleanField(verbose_name='input parameter')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Operation', verbose_name='operation')),
            ],
        ),
        migrations.CreateModel(
            name='OperationResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Operation', verbose_name='operation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='operationresource',
            unique_together=set([('operation', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='operationparameter',
            unique_together=set([('operation', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together=set([('game', 'name')]),
        ),
    ]
