# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170203_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationresource',
            name='file',
            field=models.FileField(upload_to='/nfs/', verbose_name='file'),
        ),
    ]
