# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170209_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationparameter',
            name='max_size',
            field=models.IntegerField(default=0, help_text='Use 0 for unlimited', verbose_name='max size in bytes'),
        ),
        migrations.AlterField(
            model_name='operationparameter',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='game.Operation', verbose_name='operation'),
        ),
        migrations.AlterField(
            model_name='operationresource',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='game.Operation', verbose_name='operation'),
        ),
    ]
