# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170209_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='time_limit',
            field=models.IntegerField(default=120, help_text="in seconds. WARNING: this time limit is not strict. i.e. it's possible that the system allows an operation to continue running for slightly less or more time than specified here.", verbose_name='Time limit'),
        ),
        migrations.AlterField(
            model_name='operationresource',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
