# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170210_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='manager_service',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='manager service'),
        ),
    ]
