# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_operation_manager_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationparameter',
            name='compress',
            field=models.BooleanField(default=False, verbose_name='compress?'),
        ),
    ]
