# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('docker_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerfile',
            name='cpushare',
            field=models.IntegerField(blank=True, help_text='CPU shares (relative weight)', null=True),
        ),
        migrations.AlterField(
            model_name='dockerfile',
            name='memorylimit',
            field=models.IntegerField(blank=True, help_text='maximum memory usage allowed in KBs', null=True),
        ),
    ]
