# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_registry', '0003_auto_20170208_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerfile',
            name='latest_build_and_push_log',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
