# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_registry', '0004_dockerfile_latest_build_and_push_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerfile',
            name='tar_file',
            field=models.BooleanField(default=False, verbose_name='is tar file?'),
        ),
    ]
